Add search feature #61
jonbiemond/BCIT-Flex pull request #73
Opened 2023-11-01 19:25 UTC by Dominik26-1

2023-11-01 19:58 UTC, MikeVarchola approved these changes

2023-11-02 03:23 UTC, jonbiemond requested changes
Hey @Dominik26-1, this looks awesome! Just one small change if that's alright. I can work on resolving any conflicts in the meantime.

2023-11-02 03:23 UTC, jonbiemond commented on bcitflex/model/enum.py
What do you think about refactoring this into `/app_functions/course_query.py`? All the other classes in `/model` are representations of database objects.

2023-11-02 07:28 UTC, Dominik26-1 commented on bcitflex/model/enum.py
From architecture perspective is it okay, that all classes which call or use this enum will have import dependendency from course_query.py? Do you consider keep it as separated file but change location?

2023-11-02 07:36 UTC, Dominik26-1 commented on bcitflex/model/enum.py
Done

2023-11-02 07:38 UTC, Dominik26-1 reviewed
done refactor

2023-11-02 12:51 UTC, jonbiemond approved these changes

2023-11-02 21:57 UTC, Dominik26-1 commented
Can you merge my pull request?

2023-11-03 13:52 UTC, merged